// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/events': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/events.get').default>>>>
    }
    '/api/savings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/savings.get').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/api/timeline': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/timeline.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.6_@libsql+client@0.14.0_db0@0.3.4_@libsql+client@0.14.0__ioredi_a3c05dd1c24d85101dd3b5c8cbf7ad7f/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}