// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.6_@vue+compiler-dom@3.5.34_eslint@10.4.0_jiti@2.7.0__magicast@0.5.3_ro_0f44e1fb50dd396ef0eb05b871047554/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.6_@vue+compiler-dom@3.5.34_eslint@10.4.0_jiti@2.7.0__magicast@0.5.3_ro_0f44e1fb50dd396ef0eb05b871047554/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.6_@vue+compiler-dom@3.5.34_eslint@10.4.0_jiti@2.7.0__magicast@0.5.3_ro_0f44e1fb50dd396ef0eb05b871047554/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.3_@types+node@20.19.41_jiti@2.7.0_terser@5.47.1_yaml@2.9.0__vue@3.5.34_typescript@5.9.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.3_@types+node@20.19.41_jiti@2.7.0_terser@5.47.1_yaml@2.9.0__vue@3.5.34_typescript@5.9.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.6_@biomejs+biome@1.9.4_@libsql+client@0.14.0_@parcel+watcher@2.5.6_@types+nod_6e1d18d86b63ce3c47cb83e99c1bb790/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.6_@vue+compiler-dom@3.5.34_eslint@10.4.0_jiti@2.7.0__magicast@0.5.3_ro_0f44e1fb50dd396ef0eb05b871047554/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
